# Generated by Django 4.1.5 on 2023-01-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='id',
            new_name='template_id',
        ),
        migrations.RenameField(
            model_name='template_color',
            old_name='id',
            new_name='color_id',
        ),
        migrations.RenameField(
            model_name='template_color',
            old_name='format',
            new_name='format_id',
        ),
        migrations.RenameField(
            model_name='template_color',
            old_name='template',
            new_name='template_id',
        ),
        migrations.RenameField(
            model_name='template_format',
            old_name='id',
            new_name='format_id',
        ),
        migrations.RenameField(
            model_name='template_format',
            old_name='template',
            new_name='template_id',
        ),
    ]
