# Generated by Django 4.1.5 on 2023-01-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0003_remove_template_font_remove_template_maxcharacters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template_color',
            old_name='imageURL',
            new_name='templateS3URL',
        ),
        migrations.RemoveField(
            model_name='template_format',
            name='template_id',
        ),
        migrations.AddField(
            model_name='template_format',
            name='template_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posty.template'),
            preserve_default=False,
        ),
    ]
