# Generated by Django 4.1.5 on 2023-02-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "posty",
            "0005_rename_fontcolorpunchline_template_color_fontcolordescription_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template_color",
            name="fontColorBody",
        ),
        migrations.RemoveField(
            model_name="template_color",
            name="fontColorCTA",
        ),
        migrations.RemoveField(
            model_name="template_color",
            name="fontColorDescription",
        ),
        migrations.RemoveField(
            model_name="template_format",
            name="fontBody",
        ),
        migrations.RemoveField(
            model_name="template_format",
            name="fontCTA",
        ),
        migrations.RemoveField(
            model_name="template_format",
            name="fontDescription",
        ),
        migrations.RemoveField(
            model_name="template_format",
            name="fontSizeBody",
        ),
        migrations.RemoveField(
            model_name="template_format",
            name="fontSizeCTA",
        ),
        migrations.RemoveField(
            model_name="template_format",
            name="fontSizeDescription",
        ),
        migrations.RemoveField(
            model_name="template_format",
            name="maxCharactersBody",
        ),
        migrations.RemoveField(
            model_name="template_format",
            name="maxCharactersCTA",
        ),
        migrations.RemoveField(
            model_name="template_format",
            name="maxCharactersDescription",
        ),
    ]
