# Generated by Django 4.1.5 on 2023-02-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posty", "0006_remove_template_color_fontcolorbody_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template_format",
            name="template_id",
        ),
    ]
