FROM --platform=linux/amd64 python:3.10

RUN mkdir /app
WORKDIR /app

# for chrome and chrome driver

COPY install_chrome_driver.sh /app/
RUN chmod +x install_chrome_driver.sh
RUN ./install_chrome_driver.sh

COPY server /app/
COPY requirements.txt /app/

RUN pip install -r requirements.txt


CMD python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000